# Generated by Django 5.1.4 on 2025-01-14 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('address', models.TextField(max_length=1000)),
                ('description', models.TextField(blank=True, help_text='describe what you do')),
                ('customers', models.ManyToManyField(blank=True, null=True, to='customers.customer')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
