# Generated by Django 5.1.4 on 2025-01-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.CharField(default='slug', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_paln',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
