# Generated by Django 5.1.4 on 2025-01-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_slug_business_subscription_paln_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='subscription_paln',
            new_name='subscription_plan',
        ),
    ]
