# Generated by Django 5.1.4 on 2025-01-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_business_date_joined_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff',
            new_name='business',
        ),
    ]
