# Generated by Django 5.1.4 on 2025-01-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_rename_staff_staff_business'),
        ('customers', '0003_customer_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('coupone_type', models.CharField(choices=[('redeemed individually', 'redeemed individually'), ('stacked up', 'stacked up'), ('direct ticket to a challenge', 'direct ticket to a challenge')], max_length=100)),
                ('discount', models.IntegerField(default=10, help_text='percentage discount')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('expiry_in', models.IntegerField(default=6, help_text='number of days before coupone expires')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupone', to='businesses.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
    ]
