# Generated by Django 5.1.4 on 2025-01-14 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_coupone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.staff'),
        ),
    ]
