# Generated by Django 5.1.4 on 2025-01-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_coupone_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupone',
            name='code',
            field=models.CharField(default='7c912394', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='StoreChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(choices=[('daily challenge', 'daily challenge'), ('weekly challenge', 'weekly challenge'), ('monthly challenge', 'monthly challenge'), ('yearly challenge', 'yearly challenge')], max_length=100)),
                ('challenge_name', models.CharField(max_length=200)),
                ('challenge_reward', models.CharField(help_text='whats the rewaerd for the challenge', max_length=500)),
                ('target_winners', models.IntegerField(help_text='how many winners do you want for this challenge')),
                ('day_of_the_challenge', models.DateField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.staff')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to='businesses.coupone')),
                ('winners', models.ManyToManyField(blank=True, related_name='winners', to='businesses.coupone')),
            ],
        ),
    ]
