# Generated by Django 5.1.4 on 2025-01-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_alter_coupone_code_storechallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupone',
            name='code',
            field=models.CharField(default='123wqeuy', max_length=8, unique=True),
        ),
    ]
