# Generated by Django 5.1.4 on 2025-01-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_alter_coupone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupone',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
