# Generated by Django 5.1.4 on 2025-01-14 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_alter_coupone_code'),
        ('customers', '0003_customer_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupone',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storechallenge',
            name='challenge_reward',
            field=models.CharField(help_text='whats the reward for the challenge', max_length=500),
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_value', models.IntegerField()),
                ('average_purchase_per_point', models.IntegerField(default=100)),
                ('points_earned', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='businesses.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
    ]
