# Generated by Django 5.1.4 on 2025-02-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_coupone_used_alter_storechallenge_challenge_reward_and_more'),
        ('customers', '0003_customer_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupone',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupone', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='storechallenge',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='businesses.business'),
        ),
    ]
