# Generated by Django 5.1.4 on 2025-02-02 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_alter_coupone_customer_alter_storechallenge_business'),
        ('customers', '0003_customer_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltypoint',
            name='average_purchase_per_point',
        ),
        migrations.AlterField(
            model_name='loyaltypoint',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='businesses.business'),
        ),
        migrations.CreateModel(
            name='LoyaltyPointsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('points on purchases made', 'points on purchases made'), ('points on visiting the store', 'points on visiting the store'), ('points on refferal sales', 'points on refferal sales'), ('points on bringing friends to the store', 'points on bringing friends to the store')], max_length=100)),
                ('total_value_for_a_point', models.IntegerField(help_text=' for purchase made what purchase value equals a point, for visits how many visits eaquals apoint, for refferal sales whats sales value equals a point, and for friends brought to the store how many friends equals a point')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_category', to='businesses.business')),
            ],
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.loyaltypointscategory'),
        ),
        migrations.CreateModel(
            name='RefferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferal', to='businesses.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
    ]
