# Generated by Django 5.1.4 on 2025-02-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0016_loyaltypointscategory_redemed_at_how_much_per_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypointscategory',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.staff'),
        ),
    ]
