# Generated by Django 5.1.4 on 2025-02-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0019_businesscustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscustomer',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
