# Generated by Django 5.1.4 on 2025-02-24 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0020_businesscustomer_refferal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscustomer',
            name='reffered_by',
            field=models.ForeignKey(blank=True, help_text='user who reffered customer', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesscustomer',
            name='refferal_code',
            field=models.CharField(blank=True, help_text='code customer will use to reffer other customers', max_length=8, null=True, unique=True),
        ),
    ]
