# Generated by Django 5.1.4 on 2025-03-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0021_businesscustomer_reffered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupone',
            name='coupone_apply_to',
            field=models.CharField(choices=[('all products', 'all products'), ('specific products', 'specific products')], default='all products', max_length=100),
            preserve_default=False,
        ),
    ]
