# Generated by Django 5.1.4 on 2025-03-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0022_coupone_coupone_apply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='storechallenge',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
