# Generated by Django 5.1.4 on 2025-03-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0023_storechallenge_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupone',
            name='coupone_type',
            field=models.CharField(choices=[('redeemed individually', 'redeemed individually'), ('stacked up', 'stacked up'), ('direct ticket to a challenge', 'direct ticket to a challenge'), ('refferal coupon', 'refferal coupon')], max_length=100),
        ),
    ]
