# Generated by Django 5.1.4 on 2025-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0024_alter_coupone_coupone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypoint',
            name='payement_refference_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='status',
            field=models.CharField(choices=[('awaiting approval', 'awaiting approval'), ('approved', 'approved'), ('points on refferal sales', 'points on refferal sales'), ('declined', 'declined')], default='awaiting approval', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
