# Generated by Django 5.1.4 on 2025-04-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0025_loyaltypoint_payement_refference_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoint',
            name='status',
            field=models.CharField(choices=[('awaiting approval', 'awaiting approval'), ('approved', 'approved'), ('declined', 'declined')], default='awaiting approval', max_length=100),
        ),
    ]
