# Generated by Django 5.1.4 on 2025-04-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0026_alter_loyaltypoint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=1000, help_text='price you charge for the product')),
                ('points', models.IntegerField(default=0, help_text='point cutomer earns after purchasing this product')),
                ('offer', models.TextField(blank=True, help_text='what offer are you running for these products')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.staff')),
            ],
        ),
    ]
