# Generated by Django 5.1.4 on 2025-04-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0028_scancount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypointscategory',
            name='category',
            field=models.CharField(choices=[('points on purchases made', 'points on purchases made'), ('signup points', 'signup points'), ('points on visiting the store', 'points on visiting the store'), ('points on refferal sales', 'points on refferal sales'), ('points on bringing friends to the store', 'points on bringing friends to the store')], max_length=100),
        ),
        migrations.AlterField(
            model_name='refferralcode',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferals', to='businesses.business'),
        ),
    ]
