# Generated by Django 5.1.4 on 2025-04-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0029_alter_loyaltypointscategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypointscategory',
            name='category',
            field=models.CharField(choices=[('points on purchases made', 'points on purchases made'), ('signup points', 'signup points'), ('points on visiting the store', 'points on visiting the store'), ('points from refferal sales', 'points from refferal sales'), ('points on bringing friends to the store', 'points on bringing friends to the store')], max_length=100),
        ),
    ]
