# Generated by Django 5.1.4 on 2025-02-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_loyalty_points',
            field=models.FloatField(default=0),
        ),
    ]
