# Generated by Django 5.1.4 on 2025-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
